"""
main.py — Entry point.

Usage:
  python main.py                  # single scan + dashboard
  python main.py --loop           # continuous scan (SCAN_INTERVAL_MINUTES)
  python main.py --digest         # send daily CLV digest to Telegram
  python main.py --close TRADE_ID PRICE   # manually close a paper trade
  python main.py --dashboard      # print CLV dashboard to terminal

The system runs in PAPER TRADING mode only.
No wallet, no pUSD, no real orders placed.
"""

from __future__ import annotations

import argparse
import logging
import time
from datetime import datetime, timezone

from config import SCAN_INTERVAL_MINUTES, DB_PATH
from scanner import run_scan
from tracker import (
    init_db, log_scan, open_paper_trade, rebuild_from_csv,
    auto_close_expired, close_paper_trade, print_dashboard,
)
from alerts import alert_edge_found, alert_daily_digest, alert_scan_summary
from glm_helper import (
    ensure_glm_cache, analyze_pre_match, get_latest_prematch_signals,
)
from scheduler import compute_scan_decision, schedule_summary

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("main")


def generate_status_report(path: str = DB_PATH, out: str = "STATUS.md"):
    """
    Write a human-readable Markdown dashboard to STATUS.md.
    GitHub renders this file automatically — no local Python needed.
    Updated after every scan run by GitHub Actions.
    """
    import sqlite3
    from datetime import datetime, timezone

    conn = sqlite3.connect(path)

    # ── Last scan time ──────────────────────────────────────────────────────
    last_scan = conn.execute(
        "SELECT MAX(timestamp) FROM scans"
    ).fetchone()[0] or "never"

    total_scans = conn.execute("SELECT COUNT(*) FROM scans").fetchone()[0]

    # ── Snapshot counts by time bucket ─────────────────────────────────────
    bucket_rows = conn.execute("""
        SELECT time_bucket, COUNT(DISTINCT market_id), COUNT(*)
        FROM scans
        WHERE time_bucket IS NOT NULL
        GROUP BY time_bucket
        ORDER BY
          CASE time_bucket
            WHEN 'T-1h'   THEN 1
            WHEN 'T-24h'  THEN 2
            WHEN 'T-168h' THEN 3
            ELSE 4 END
    """).fetchall()

    # ── Open positions ──────────────────────────────────────────────────────
    open_trades = conn.execute("""
        SELECT question, entry_price, entry_timestamp
        FROM paper_trades WHERE outcome='PENDING'
        ORDER BY entry_timestamp
    """).fetchall()

    # ── CLV summary ─────────────────────────────────────────────────────────
    clv_row = conn.execute("""
        SELECT COUNT(*),
               SUM(CASE WHEN outcome='BEAT_LINE' THEN 1 ELSE 0 END),
               ROUND(AVG(COALESCE(clv_adjusted, clv)), 4),
               ROUND(AVG(clv), 4),
               ROUND(MIN(COALESCE(clv_adjusted, clv)), 4),
               ROUND(MAX(COALESCE(clv_adjusted, clv)), 4),
               ROUND(AVG(COALESCE(time_value_baseline, 0)), 6)
        FROM paper_trades WHERE outcome != 'PENDING'
    """).fetchone()

    # ── Top advancement markets by price (most interesting = near 0.5) ─────
    market_rows = conn.execute("""
        SELECT s.question, s.poly_mid, s.volume_usd, s.spread_pct, s.timestamp
        FROM scans s
        INNER JOIN (
            SELECT market_id, MAX(timestamp) AS latest
            FROM scans GROUP BY market_id
        ) latest ON s.market_id = latest.market_id AND s.timestamp = latest.latest
        WHERE lower(s.question) LIKE '%advance%'
           OR lower(s.question) LIKE '%qualify%'
           OR lower(s.question) LIKE '%knockout%'
        ORDER BY ABS(s.poly_mid - 0.5) ASC
        LIMIT 15
    """).fetchall()

    conn.close()

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── Build markdown ───────────────────────────────────────────────────────
    lines = [
        f"# Polymarket CLV Tracker — Status Report",
        f"",
        f"> Auto-generated by GitHub Actions · Last updated: **{now}**",
        f"> Last scan: `{last_scan[:19] if last_scan != 'never' else 'never'}` · "
        f"Total snapshots: **{total_scans:,}**",
        f"",
        f"---",
        f"",
        f"## 📊 Snapshot Inventory (Multi-Timepoint)",
        f"",
        f"| Time Bucket | Unique Markets | Total Rows | Purpose |",
        f"|---|---|---|---|",
    ]

    bucket_desc = {
        "T-1h":    "CLV entry point (most informed price)",
        "T-24h":   "Narrative peak (24h before kickoff)",
        "T-168h":  "Far-from-resolution (bias zone)",
        "T-other": "Continuous monitoring",
        "T-expired": "Already resolved",
    }
    for bucket, n_markets, n_rows in bucket_rows:
        desc = bucket_desc.get(bucket, "")
        lines.append(f"| `{bucket}` | {n_markets} | {n_rows:,} | {desc} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## 🏦 CLV Summary",
        f"",
    ]

    n_resolved = clv_row[0] if clv_row else 0

    if n_resolved == 0:
        lines.append(f"**No resolved trades yet.** Waiting for matches to complete.")
        lines.append(f"")
        lines.append(f"> 🕒 CLV data accumulates automatically as matches resolve.")
    else:
        beat = clv_row[1] or 0
        avg_adj = clv_row[2]
        avg_raw = clv_row[3]
        worst = clv_row[4]
        best = clv_row[5]
        lockup = clv_row[6] or 0
        win_rate = beat / n_resolved if n_resolved > 0 else 0

        from tracker import _get_all_clv_adjusted
        import statistics
        vals = _get_all_clv_adjusted(path)
        stdev = statistics.pstdev(vals) if len(vals) > 1 else 0.0
        std_err = stdev / (n_resolved ** 0.5) if n_resolved > 0 and stdev > 0 else 0.0
        t_stat = (avg_adj / std_err) if std_err > 0 and avg_adj is not None else 0.0

        lines += [
            f"| Metric | Value |",
            f"|---|---|",
            f"| Resolved trades | **{n_resolved}** |",
            f"| Beat closing line | {beat} ({win_rate:.0%}) |",
            f"| Avg CLV (raw) | `{avg_raw:+.4f}` |",
            f"| Avg lockup discount | `{lockup:+.6f}` (RFR 5.3% × days/365) |",
            f"| **Avg CLV (adjusted)** | **`{avg_adj:+.4f}`** ← decision gate |",
            f"| Std err / t-stat | `{std_err:.4f}` / `{t_stat:.2f}` |",
            f"| Range | `{worst:+.3f}` to `{best:+.3f}` |",
            f"",
        ]

        # Decision gate verdict
        if n_resolved < 30:
            verdict = f"⏳ **INSUFFICIENT SAMPLE** — n={n_resolved}/30 minimum"
        elif avg_adj is not None and avg_adj <= 0:
            verdict = f"🛑 **PROJECT STOP SIGNAL** — clv_adjusted={avg_adj:+.3f} ≤ 0"
        elif t_stat < 2.0:
            verdict = f"⚠️ **NOT SIGNIFICANT** — t={t_stat:.2f} < 2.0 (noise)"
        elif n_resolved < 100:
            verdict = f"🟡 **PROMISING** — t={t_stat:.2f}, keep collecting (n={n_resolved}/100)"
        else:
            verdict = f"✅ **EDGE SUPPORTED** — t={t_stat:.2f}, n={n_resolved}"

        lines += [f"### Verdict", f"", f"{verdict}", f""]

    lines += [
        f"---",
        f"",
        f"## 📋 Open Positions ({len(open_trades)})",
        f"",
    ]

    if open_trades:
        lines.append(f"| Market | Entry Price | Opened |")
        lines.append(f"|---|---|---|")
        for q, entry, ts in open_trades[:20]:
            short_q = q[:55] + "…" if len(q) > 55 else q
            lines.append(f"| {short_q} | `{entry:.3f}` | {ts[:16]} |")
    else:
        lines.append(f"*No open positions. "
                     f"Positions open automatically at T-1h before each match.*")

    lines += [
        f"",
        f"---",
        f"",
        f"## 🎯 Advancement Markets (sorted by distance from 0.5)",
        f"",
        f"Markets nearest to coin-flip are most sensitive to narrative bias.",
        f"",
        f"| Team | Poly Mid | Volume | Spread |",
        f"|---|---|---|---|",
    ]

    for q, mid, vol, spread, _ in market_rows:
        team = q.replace("Will ", "").replace(" advance to the knockout stages at the 2026 FIFA World Cup?", "")
        team = team.replace(" advance to the knockout stages at the 2026 FIFA World Cup", "")
        dist = abs(mid - 0.5)
        flag = " 🎯" if dist < 0.08 else ""
        lines.append(
            f"| {team}{flag} | `{mid:.3f}` | ${vol:,.0f} | {spread:.1%} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"*Strategy: measure CLV (entry @ T-1h vs. resolution price) "
        f"across advancement markets. Gate: clv\\_adjusted > 0, t > 2, n ≥ 30.*",
    ]

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    log.info("Status report written to %s (%d lines)", out, len(lines))


# ── Core single-scan orchestration ────────────────────────────────────────────

def execute_scan(send_summary: bool = False) -> list:
    """
    Run one full scan, persist results, send edge alerts,
    and trigger GLM pre-match analysis for T-24h / T-1h markets.

    Uses the smart scheduler to decide scan depth:
      full_news  → everything (Polymarket + football-data + Tavily + GLM)
      full_live  → Polymarket + football-data (match in progress)
      full_pre   → Polymarket + football-data + GLM (no Tavily)
      light      → Polymarket prices only
      skip       → exit immediately (no matches in relevant window)
    """
    log.info("── Scan start ──────────────────────────────────")
    ensure_glm_cache(DB_PATH)

    # ── Smart scheduling decision ─────────────────────────────────────────────
    decision = compute_scan_decision(DB_PATH)
    log.info(schedule_summary(decision))

    # ── Bootstrap guard: if DB has no scan data yet, run regardless ───────────
    # On first-ever run (or after complete data loss), the scheduler returns
    # "skip" because there are no advancement markets to derive kickoff times
    # from. Without this bypass, the system would never populate itself.
    if decision.mode == "skip":
        import sqlite3 as _sq
        n = _sq.connect(DB_PATH).execute("SELECT COUNT(*) FROM scans").fetchone()[0]
        if n == 0:
            log.info("Bootstrap: empty DB — running initial full scan to populate")
            decision.mode          = "light"   # minimal: just get market data
            decision.use_news      = False
            decision.use_glm       = False
            decision.use_football_data = False
        else:
            log.info("── Skipped (no active match window) — %s", decision.reason)
            return []

    snapshots = run_scan()

    if not snapshots:
        log.warning("Scan returned 0 snapshots — check API keys and network")
        return []

    # Persist every snapshot to DB
    for snap in snapshots:
        log_scan(snap)

    # Auto-close trades that have reached resolution
    auto_close_expired(snapshots)

    # ── Open paper trades ──────────────────────────────────────────────────
    #
    # Two distinct triggers:
    #
    # 1. ALERT TRADE (alertable=True): a genuine edge signal exists
    #    (net_edge > 4%, spread < 3%). Send Telegram alert + open position.
    #
    # 2. CLV TEST ENTRY (T-1h advancement market): no edge signal required.
    #    Open a virtual position for EVERY advancement market at T-1h.
    #    This is the primary data collection mechanism — entry price at T-1h
    #    vs. resolution price = CLV. Without this, the system collects zero
    #    CLV data (all advancement markets have no_advance_baseline, so
    #    alertable is always False for them).
    #
    # Both types use open_paper_trade() and are tracked identically.
    # Only alert trades generate Telegram notifications.

    new_signals   = 0
    clv_entries   = 0

    for snap in snapshots:
        is_advance = any(
            k in snap.question.lower()
            for k in ("advance", "qualify", "knockout", "reach the")
        )

        if snap.alertable:
            # ── Edge signal: alert + open ──
            trade_id = open_paper_trade(snap, direction="YES")
            snap.paper_trade_id = trade_id
            alert_edge_found(snap, trade_id)
            new_signals += 1

        elif is_advance and snap.time_bucket == "T-1h":
            # ── CLV test entry: open without alerting ──
            # This is the 1-hour-before-kickoff virtual position.
            # Resolution price (auto-closed when price ≥ 0.95 or ≤ 0.05)
            # minus this entry price = CLV timing signal.
            trade_id = open_paper_trade(snap, direction="YES")
            snap.paper_trade_id = trade_id
            clv_entries += 1
            log.info(
                "CLV entry [T-1h] %s @ %.3f (spread=%.1f%%)",
                snap.question[:45], snap.poly_ask_vwap, snap.spread_pct * 100,
            )

    # ── GLM pre-match analysis for T-24h / T-1h advancement markets ──────────
    # Only run if scheduler says use_glm (mode=full_news or full_pre)
    prematch_buckets = {"T-24h", "T-1h"}
    glm_count = 0
    if decision.use_glm:
        for snap in snapshots:
            if snap.time_bucket not in prematch_buckets:
                continue
            is_advance_q = any(
                k in snap.question.lower()
                for k in ("advance", "qualify", "knockout", "reach the")
            )
            if not is_advance_q:
                continue
            from scanner import extract_team
            team = extract_team(snap.question)
            if team:
                # Fetch live context only if scheduler says use_news
                live_ctx = None
                if decision.use_news:
                    try:
                        from news_fetcher import fetch_live_context
                        live_ctx = fetch_live_context(team)
                    except Exception as e:
                        log.debug("news_fetcher unavailable for %s: %s", team, e)
                analyze_pre_match(
                    market_id=snap.market_id, team=team,
                    poly_price=snap.poly_mid, hours_to_end=snap.hours_to_end,
                    path=DB_PATH, live_context=live_ctx,
                )
                glm_count += 1
    if glm_count:
        log.info("GLM analysed %d markets (mode=%s, news=%s)",
                 glm_count, decision.mode, decision.use_news)

    if send_summary:
        alert_scan_summary(snapshots)

    log.info(
        "── Scan done: %d markets | %d edge signals | %d CLV test entries ──",
        len(snapshots), new_signals, clv_entries,
    )
    return snapshots


# ── CLI ────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Polymarket edge scanner (paper trading)")
    p.add_argument("--loop",      action="store_true",
                   help="Run continuously every SCAN_INTERVAL_MINUTES minutes")
    p.add_argument("--interval",  type=int, default=SCAN_INTERVAL_MINUTES,
                   help="Override scan interval in minutes (default: %(default)s)")
    p.add_argument("--digest",    action="store_true",
                   help="Send daily CLV digest to Telegram and exit")
    p.add_argument("--dashboard", action="store_true",
                   help="Print CLV dashboard to terminal and exit")
    p.add_argument("--close",     nargs=2, metavar=("TRADE_ID", "PRICE"),
                   help="Manually close a paper trade: --close TRADE_ID 0.82")
    p.add_argument("--summary",   action="store_true",
                   help="Also send scan-summary Telegram ping each run")
    p.add_argument("--report",    action="store_true",
                   help="Write STATUS.md dashboard (readable on GitHub, no scan)")
    return p.parse_args()


def main():
    init_db(DB_PATH)
    rebuild_from_csv(path=DB_PATH)
    args = parse_args()

    # ── Report generation (no scan, just read DB) ─────────────────────────
    if args.report:
        generate_status_report()
        return

    # ── Manual close ──────────────────────────────────────────────────────────
    if args.close:
        trade_id, price_str = args.close
        try:
            price = float(price_str)
        except ValueError:
            log.error("Invalid price: %s", price_str)
            return
        close_paper_trade(trade_id, price, DB_PATH)
        print_dashboard()
        return

    # ── Daily digest ──────────────────────────────────────────────────────────
    if args.digest:
        alert_daily_digest()
        return

    # ── Dashboard only ────────────────────────────────────────────────────────
    if args.dashboard:
        print_dashboard()
        return

    # ── Single scan ───────────────────────────────────────────────────────────
    if not args.loop:
        execute_scan(send_summary=args.summary)
        print_dashboard()
        return

    # ── Continuous loop ───────────────────────────────────────────────────────
    interval_sec = args.interval * 60
    log.info(
        "Continuous mode: scanning every %d minutes. Ctrl+C to stop.",
        args.interval,
    )

    scan_count = 0
    while True:
        try:
            execute_scan(send_summary=args.summary)
            scan_count += 1

            # Print dashboard every 4 scans (~2 hours at default interval)
            if scan_count % 4 == 0:
                print_dashboard()

            next_run = datetime.now(timezone.utc).strftime("%H:%M UTC")
            log.info("Sleeping %d min. Next run ~%s", args.interval, next_run)
            time.sleep(interval_sec)

        except KeyboardInterrupt:
            log.info("Stopped by user.")
            print_dashboard()
            break
        except Exception as e:
            log.error("Scan failed: %s — retrying in 5 min", e, exc_info=True)
            time.sleep(300)


if __name__ == "__main__":
    main()
